### ISSUE TITLE
Is possible to make the structure/syntax of smart contract similar to substrate runtime module?

### ISSUE THREAD

**Issue by xlc** [Robbepop/pdsl#46]
If possible, I want to see the syntax, structure, ABI, overall architecture for smart contract as similar to substrate runtime module as possible.
This will reduce the fraction for developers to learn contract and runtime module.

A common scenario is: a developer chose to make a runtime / contract initially, then later figure out it is better to be contract / runtime instead. The amount of work to convert it between runtime and contract should be minimal.

Another scenario: it will be trivial to securely merge multiple parachains into one, just deploy them as smart contract.

This also means contract developers are runtime developers and vice visa, means we have more contract developers and more runtime developers.

Also the substrate runtime already have metadata system, which is basically the ABI (it is missing encoding information but can be fixed by https://github.com/paritytech/substrate/pull/1328). It will be good if the similar system is used instead of invent another one.

**Comment by Robbepop** [comment]
We already have discussed this several times how much we want alignment with the rest of Substrate. In the end we are designing an eDSL for smart contracts which at its heart targets simplicity and readability of smart contract code.

It is a very opinionated topic and I cannot see a majority on either side at the moment.
On the other side we are free to design more eDSL on top of `pdsl_core` and `pdsl_model` besides the current one if you dislike it.

Concerning the ABI, I have not yet looked into its compatibility with smart contracts. For now we want to have a very simple way to communicate smart contract API with its very limited set of types. We use that for UI stuff as well as later for depending on other smart contracts.

**Comment by hammeWang** [comment]
as an eth contract developer, I prefer pDSL. The syntax is easy to understand without any explanation, very much like solidity but organized in a rust way.
Once pDSL can be used in production, I would like to rewrite all my ethereum contracts.

**Comment by xlc** [comment]
Make sense. I will leave this open because compile runtime module to contract is still a useful thing to have. But I do agree its use cases are more limited.

Feel free to chose this issue if you have decided to not do this.

**Comment by Robbepop** [comment]
I think I will close this since this will be either a long-term issue or just another project that is yet another pDSL for smart contracts.
