### ISSUE TITLE
Is possible to have helper/private method implemented outside `contract` macro?

### ISSUE THREAD

**Issue by xlc** [Robbepop/pdsl#48]
Last time I tried, VSCode and CLion is having trouble debug code inside macro. I think it is because the code in the macro can get modified in such way confused the IDE.

So I want to have most of the logic outside macro and only the interface and delegation call in macro.

I think it is already possible, just want to make sure this point is considered in the design of the contract syntax.

**Comment by Robbepop** [comment]
Currently all contract definitions have to be contained within the macro body `contract!`.
There are no plans to change this in the near future.

**Comment by xlc** [comment]
ok. It will be good if there is a workaround for it. But I am ok as it is.
